### ISSUE TITLE
[基本ゲームプレイ] 1.4 / テトリミノの左右移動を実装

### ISSUE THREAD

**Issue by uki-t66** [teamdev-black/Tetris#8]
## 📋 説明
テトリミノをキーボードで左右移動させるためのロジックを実装。

[]テトリスをプレイするためのキーボードを準備する。
[]キーボード操作によるテトリミノの移動を可能にする。

## 受け入れ条件（完了の定義）
・キーボード操作でテトリミノを左右に移動させることができる。

## 📅 期限
完了予定日: 2024-9-20

## 👥 担当者
担当: @uki-t66 

## 🏷 ラベル
feature
## 🔗 関連リソース
- 関連仕様: 関連仕様: docs/functional-requriements.md: 1.4 左右移動

**Comment by miguellords** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by uki-t66** [comment]
done
